### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Fedeorlandau** [skegel13/vue-password#1]
Hi!

I'm trying to use this module with Vue.js 2 but vue-loader can't find it. I've tried another modules like vue-password-strength-meter and they are working. 

`Module not found: Error: Cannot resolve module 'vue-password'  @ multi vendor`

Thanks and well played.

**Comment by skegel13** [comment]
Can you show me your code where you importing the module? I have not run into this problem on my side.

**Comment by Fedeorlandau** [comment]
I'm not importing it yet. Just add it to entry vendor on Webpack.

**Comment by Fedeorlandau** [comment]
```
let path = require('path');
let Webpack = require('webpack');
var ExtractTextPlugin = require("extract-text-webpack-plugin")

const config = {
  entry: {
    app: './src/app.js',
    vendor: ['vue', 'axios', 'vue-password-strength-meter', 'vue-password']
  },

  output: {
    path: path.resolve(__dirname, 'public/js'),
    filename: '[name].js'
  },

  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel'
      },
      {
        test: /\.s(a|c)ss$/,
        loader: ExtractTextPlugin.extract("style", "css!postcss!sass?outputStyle=compressed")
      },
      {
        test: /\.vue$/,
        loader: 'vue'
      }
    ]
  },

  // vue-loader configuration
  vue: {
    loaders: {
      sass: ExtractTextPlugin.extract('css!postcss!sass?outputStyle=compressed')
    }
  },

  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.common.js',
      'styles': path.resolve(__dirname, './src/styles/')
    }
  },

  plugins: [
    new Webpack.optimize.CommonsChunkPlugin({name: 'vendor'}),
    new ExtractTextPlugin('../css/[name].css')
  ]
};

if (process.env.NODE_ENV === 'production') {
  config.plugins.push(
    new Webpack.optimize.UglifyJsPlugin({
      sourcemap: true,
      compress: {
        warnings: false
      }
    })
  );
}

module.exports = config;

```

**Comment by skegel13** [comment]
OK. Are you getting the error when you run Webpack then? If so, make sure you have installed the library. Is there a 'vue-password' folder in your node_modules folder?

**Comment by Fedeorlandau** [comment]
Yes, i've installed it with `yarn add vue-password`. It's on node_modules.
It's super weird. Other libs work perfect .
Thanks for your reply.

**Comment by skegel13** [comment]
Interesting, I am looking into it.

Out of curiosity, are you using Webpack 1 or Webpack 2? I haven't tried to import it with Webpack 1 and I would recommend using Webpack 2 if you aren't already.

**Comment by Fedeorlandau** [comment]
I'm using webpack 1. I'll try migrating to webpack 2.
Thanks

**Comment by Cosmicist** [comment]
Hi @skegel13! This is happening to me as well—although we are working on the same project 😄.
I found a temporary fix for this, on the webpack config use `'vue-password/dist'` and import it the same way: `import VuePassword from 'vue-password/dist'` and that seems to work...
It looks like for some reason webpack is not recognizing the `main` entry on the `package.json` of this lib.
We're using webpack 1, but we are planning to migrate to webpack 2, maybe that has something to do, wouldn't surprise me. We'll try again once we migrate to webpack 2 and see how it goes.
Thank you!

**Comment by skegel13** [comment]
Sounds good. I will see what I can find out with Webpack 1.

Also, for Vue applications, https://github.com/vuejs/vue-cli is very good at setting up a boilerplate with the Webpack configuration already setup. That is actually where I started when I built the component.

**Comment by skegel13** [comment]
It looks like it was both a problem with the 'main' entry in the package.json and webpack 1. I changed the main entry from '/dist/index.js' to './dist/index.js' and that seems to have solved the issue.

I still recommend upgrading to Webpack 2, but it should work in Webpack 1 now with version 0.0.10.

**Comment by Cosmicist** [comment]
Awesome! Thanks! Yeah, we will definitely migrate to webpack 2.
