### ISSUE TITLE
Error in callback for watcher "userInputs"

### ISSUE THREAD

**Issue by halostatue** [skegel13/vue-password#12]
I’m getting this message in some cases when using vue-password with the detail of `"TypeError: null is not an object (evaluating 'e.length')"`.  The problem is actually in the `passwordStrength` function of zxcvbn, but how it gets called matters:

```js
    watch: {
      /**
       * Watch for changes in the user inputs prop to update the strength score.
       */
      userInputs () {
        this.strength = passwordStrength(this.value, this.userInputs)
      }
    },
```

In this case`this.value` is being changed to `e` in the minified version of the file, and `passwordStrength` is checking `e.length`. In the case where I’ve seen this, `e === null`.

I believe that the patch here would be:

```javascript
    watch: {
      /**
       * Watch for changes in the user inputs prop to update the strength score.
       */
      userInputs () {
        if (this.value == null) {
          this.strength = 0
        } else {
          this.strength = passwordStrength(this.value, this.userInputs)
        }
      }
    },
```

**Comment by skegel13** [comment]
I made this change and released a new version
