### ISSUE TITLE
Keyup events

### ISSUE THREAD

**Issue by dbeja** [skegel13/vue-password#13]
Hi,

Is it possible to add keyup events like:

```
<vue-password` @keyup.enter="dosomething"></vue-password>
```

**Comment by skegel13** [comment]
Try using @keyup.native.enter instead and see if that works. If not, I will try doing something with v-on="$listeners" but I know there was some issues with that in the past.

**Comment by dbeja** [comment]
Perfect, it worked with "native".

Thanks a lot!
