### ISSUE TITLE
Can the input be slotted too?

### ISSUE THREAD

**Issue by moltar** [skegel13/vue-password#15]
Would be nice if `input` supported the slotted option too, otherwise some use cases are not possible. 

E.g. using it with Bootstrap Vue and `b-input-group-prepend` is not possible:

```html
<b-input-group>
  <b-input-group-prepend>  <-- this tag has to be immediately
    <b-input-group-text>       adjacent to the input tag
      <fa-icon icon="at" />    or it does't work
    </b-input-group-text>
  </b-input-group-prepend>
  <vue-password
    v-model="password"
    :user-inputs="[email]"
    classes="form-control"
  />
</b-input-group>
```

Results in:

![](http://take.ms/r6f7u)

But should look like this:

![](http://take.ms/SAFLM)

Thanks!

**Comment by skegel13** [comment]
I will try to add this slot this weekend.

**Comment by skegel13** [comment]
This has been added in version 1.2.0 100a9472b6297415a6a8ac2e86a1958d3771ca15

See the README for the available items in the slot scope and a simple example using Bulma.

**Comment by moltar** [comment]
Can't get it to work with Bootstrap decorations:

```html
              <vue-password
                v-model="password"
                :user-inputs="[email]">
                <div
                  slot="password-input"
                  slot-scope="props"
                >
                  <div class="input-group mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text">@</span>
                    </div>
                    <input
                      :value="props.value"
                      class="form-control"
                      type="password"
                    >
                  </div>
                </div>
              </vue-password>
```

Results in the following HTML:

http://take.ms/S7a4F

Looks like this:

http://take.ms/Rz8wt

Any ideas?

Thank you!

**Comment by skegel13** [comment]
It looks like the slot is being ignored. I will take a look tongiht and see if I can figure it out.

In the meantime, make sure your versions of Vue and VuePassword are updated.

**Comment by moltar** [comment]
Oops, you are right! The package was not up-to-date.

**Comment by moltar** [comment]
Thanks!!! 👍
