### ISSUE TITLE
Password toggle hides when input is in focus

### ISSUE THREAD

**Issue by moltar** [skegel13/vue-password#16]
I am not sure if this is a feature or a bug, but the toggle disappears when input is in focus. I think it should stay visible.

Demo: http://take.ms/9DtfoF

**Comment by skegel13** [comment]
My guess is this has something to do with Bootstrap's styling and possibly z-index. Use the inspector and see if the toggle is still there, just behind the input box.

I can take a look later as well.

**Comment by moltar** [comment]
It does appear to be a `z-index` issue. Setting the `.VuePassword__Toggle` to an arbitrary high number fixes the issue.

But at the same time, I am not seeing any `z-index` settings on the `input` field.

**Comment by skegel13** [comment]
This is indeed being caused by Bootstrap. It has the following css:

```
.input-group > .custom-file .custom-file-input:focus ~ .custom-file-label, .input-group > .custom-select:focus, .input-group > .form-control:focus {
    z-index: 3;
}
```
