### ISSUE TITLE
Require minimum strength?

### ISSUE THREAD

**Issue by haayman** [skegel13/vue-password#18]
Hi,

I'd like to force a good password, so simply displaying the strength doesn't cut it. I'd like to get some feedback about the strength and only enable the submit button if the strength is high enough. Is this already possible with this component?

**Comment by skegel13** [comment]
I could probably add an event to fire whenever the strength changes. You could then listen to that event to set the score, and whenever it reaches a certain point, enable the submit button.

There are ways to do this currently, but not necessarily best practices.
