### ISSUE TITLE
Password placeholder

### ISSUE THREAD

**Issue by craigwillis85** [skegel13/vue-password#2]
Hi

Is there a way add a `placeholder="blah"` tag within the `<input>` field?

Thanks

**Comment by skegel13** [comment]
At this time, there is not a way to include a placeholder. Shouldn't be hard to do. Hopefully I can get something later today or tomorrow.

**Comment by craigwillis85** [comment]
Hi

I managed to add a placeholder. I'm not sure what is the right way to submit a pull request, since i had to edit the `dist/index.js`file

**Comment by skegel13** [comment]
The dist/index.js file is a built using Webpack, so it should not be manually edited. I will go in later and update the source and rebuild it.

**Comment by craigwillis85** [comment]
You might want to close the pull request then, I wasn't sure what file to edit.

**Comment by craigwillis85** [comment]
Ok, I've re-submitted a pull request with the correct configuration.

It should build and add the placeholder into `dist/index.js`

**Comment by skegel13** [comment]
Placeholder attribute added in version 0.0.11
