### ISSUE TITLE
Tabindex on the password toggle

### ISSUE THREAD

**Issue by 22Nick22** [skegel13/vue-password#38]
After typing in a password, hitting tab navigates you onto the password toggle now that it is a `<button>`. I believe this element should have `tabindex="-1"` by default for expected behaviour when filling out a form.

**Comment by JJCLane** [comment]
I was thinking about that too, but how would a keyboard user toggle the password in that case?

**Comment by skegel13** [comment]
Yeah, this is interesting. I am not sure what the best solution is here. I was looking at Edge which will automatically put in the 'eye' to see a password and it does not let you tab into it so maybe that's the way to go?

I've seen other instances where other elements or <a> elements without an 'href' is used, but I think <button> makes more sense for semantics and accessibility. Just not sure about the focus.

I am open to setting it to `tabindex="-1"` but I would like to hear some more feedback.

**Comment by JJCLane** [comment]
I just checked a few large companies who have the show password feature and they are all implemented as buttons that take focus:

- [LinkedIn](https://www.linkedin.com/login?fromSignIn=true&trk=guest_homepage-basic_nav-header-signin)
- [Adobe](https://auth.services.adobe.com/en_US/index.html?callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fadobeid%2Fadobedotcom2%2FAdobeID%2Ftoken%3Fredirect_uri%3Dhttps%253A%252F%252Fwww.adobe.com%252Findex2.html%2523from_ims%253Dtrue%2526old_hash%253D%2526api%253Dauthorize%26state%3D%257B%2522ac%2522%253A%2522%2522%257D&client_id=adobedotcom2&scope=creative_cloud%2CAdobeID%2Copenid%2Cgnav%2Cread_organizations%2Cadditional_info.projectedProductContext%2Csao.ACOM_CLOUD_STORAGE%2Csao.stock%2Csao.cce_private%2Cadditional_info.roles&denied_callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fdenied%2Fadobedotcom2%3Fredirect_uri%3Dhttps%253A%252F%252Fwww.adobe.com%252Findex2.html%2523from_ims%253Dtrue%2526old_hash%253D%2526api%253Dauthorize%26response_type%3Dtoken%26state%3D%257B%2522ac%2522%253A%2522%2522%257D&state=%7B%22ac%22%3A%22%22%7D&relay=80ed05bb-bd6d-4f51-b8da-8c44b396bde3&locale=en_US&flow_type=token&idp_flow_type=login#/)
- [PayPal](https://www.paypal.com/us/signin)

**Comment by skegel13** [comment]
So I think based on that @JJCLane, I am going to leave as is. @22Nick22, if you really want to add this, you can use the `password-toggle` scoped slot.
