### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by frandiox** [skegel13/vue-password#5]
Hi! Thanks a lot for this package. Would you consider adding `$listeners` directly to the `input` element?

I have an icon on the left side of the input (with Bulma) and I'd like it to change its color when the input is focused. Due to the DOM structure, I think it is not possible to use a CSS selector for this. Also, since `focus` and `blur` events do not bubble, we cannot add `@focus.native` to the component. Therefore, it would be nice if you can set `<input v-on="$listeners">` or something similar. Notice that this feature was added in `vue@2.4.0`, it would not work before that version.

Thanks!

**Comment by skegel13** [comment]
I can look into this. I haven't used the new $listeners and $attrs properties yet. Would I just be adding it to the password input element of the component? Would $attrs be helpful as well?

**Comment by skegel13** [comment]
Added in version v1.0.0 7a5c0527d88429f85b73420cc02fde9f814be4b8

**Comment by frandiox** [comment]
@skegel13 Hey! Thanks for the update. However, I believe the dist file is not updated. I cannot see any `$listeners` or `$attrs` in the generated code. It works when I clone the repo and build it myself.
https://unpkg.com/vue-password@1.0.0/dist/index.js

**Comment by skegel13** [comment]
You're right, I forgot to rebuild the files. I added the files and set the version to 1.0.1.
