### ISSUE TITLE
Dyanamically generated password fails to update the password meter

### ISSUE THREAD

**Issue by Geowan** [skegel13/vue-password#8]
Am setting up my password like

         <vue-password v-model="account_settings_form.password"
                                          name="password"
                                          v-validate="'required'"
                                          placeholder="Password"
                            >
                            </vue-password>

Now am setting the value of account_settings.password dynamically but this doesnt update the meter

like
       this.account_settings.password = randomstring//this doesnt work

How do i go about this

**Comment by skegel13** [comment]
I'm guessing by updating the password outside of the component, it doesn't throw the input event which is needed to update the strength meter.

I will look into how to resolve this.

**Comment by skegel13** [comment]
I started looking into this and I updated the password outside of the component and the meter updated.

Looking at your example, you have v-model set to `account_settings_form.password` but everywhere else, you reference `account_settings.password` could that be the issue?

Also make sure you update Vue. It should be at least 2.4.2.

**Comment by moayadfarhan1** [comment]
I have the same issue dude,

` <vue-password  :data-vv-as="$t('password')" classes="form-control mb-3" v-model="password" :score="score"  v-validate="'required|max:20'"   :strengthMessages="strengthMessages"   @input="updateScore" :placeholder="$t('Common.password')" >
   </vue-password>`

` methods: {
    updateScore : function (password) {
            if (password.length > 7) {

                this.score = 4
            } else {
                 this.score = 3
            }  
     }`
![cashu_-_2018-08-09_13 26 28](https://user-images.githubusercontent.com/35889183/43893510-e6adf626-9bd7-11e8-88aa-c6a51da4ad2e.png)


currently score= 3; the expected result meter score   3
